//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EiSorteei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilhetesCarrinho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BilhetesCarrinho()
        {
            this.OrderBumpsEscolhidos = new HashSet<OrderBumpsEscolhidos>();
        }
    
        public long Id { get; set; }
        public long IdCarrinho { get; set; }
        public int NumeroBilhete { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Carrinho Carrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBumpsEscolhidos> OrderBumpsEscolhidos { get; set; }
    }
}
