//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EiSorteei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilhetesCarrinho
    {
        public long Id { get; set; }
        public long IdCarrinho { get; set; }
        public int NumeroBilhete { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Carrinho Carrinho { get; set; }
    }
}
