//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EiSorteei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public long OrderID { get; set; }
        public long UsuarioId { get; set; }
        public long ProdutoId { get; set; }
        public string CodigoVendedor { get; set; }
        public System.DateTime DataCompra { get; set; }
        public string IdCompra { get; set; }
        public string NumeroRifa { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
