//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EiSorteei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBumpsEscolhidos
    {
        public long Id { get; set; }
        public long IdBilhete { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public long IdOrderBump { get; set; }
    
        public virtual BilhetesCarrinho BilhetesCarrinho { get; set; }
        public virtual OrderBump OrderBump { get; set; }
    }
}
