//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EiSorteei.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Multimidia = new HashSet<Multimidia>();
            this.Carrinho = new HashSet<Carrinho>();
            this.TempBilhetes = new HashSet<TempBilhetes>();
        }
    
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public long IdCategoria { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int RangeCodigo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
        public bool Status { get; set; }
        public decimal ValorRifa { get; set; }
        public Nullable<System.DateTime> DataSorteio { get; set; }
        public string Video { get; set; }
    
        public virtual CategoriaProduto CategoriaProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multimidia> Multimidia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempBilhetes> TempBilhetes { get; set; }
    }
}
